version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "Running linting..."
      - npm run lint
      - echo "Running tests..."
      - npm test
  build:
    commands:
      - echo "Build started on `date`"
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: 'build' #muss noch angepasst werden
